// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateNewFile(arg1:Array<any>):Promise<void>;

export function DeleteQuestionFile(arg1:Array<any>):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function ReadAllfiles():Promise<Array<main.File>>;

export function ReadQuestionFile(arg1:string):Promise<main.Questions>;

export function WriteQuestionFile(arg1:Array<any>):Promise<void>;
