// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Greet(arg1:string):Promise<string>;

export function ReadAllfiles():Promise<Array<main.File>>;

export function StartInterview(arg1:string):Promise<main.Questions>;
