// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ReadAllfiles() {
  return window['go']['main']['App']['ReadAllfiles']();
}

export function ReadQuestionFile(arg1) {
  return window['go']['main']['App']['ReadQuestionFile'](arg1);
}

export function WriteQuestionFile(arg1) {
  return window['go']['main']['App']['WriteQuestionFile'](arg1);
}
